spring:
  config:
    import:
      - classpath:feign-config-local-was.yaml
images:
  upload-root: ./tmp/dailyfeed/store/images
  max-width: 350
  max-height: 350
  thumbnail-size: 150
  quality: 0.85
server:
  port: 8085